name: ElysiaPotion
version: '${project.version}'
main: elysia.ElysiaPotion
softdepend:
  - AttributePlus
  - PlaceholderAPI
  - SkillAPI
  - DragonCore
commands:
  ElysiaPotion:
    aliases:
      - ep